---
- include: debian/docker.yml
  when: ansible_os_family == 'Debian'

- include: osx/docker.yml
  when: ansible_os_family == 'Darwin'

- include: debian/machine.yml
  when: docker_install_machine and ansible_os_family == 'Debian'

- include: osx/machine.yml
  when: docker_install_machine and ansible_os_family == 'Darwin'

- include: debian/compose.yml
  when: docker_install_compose and ansible_os_family == 'Debian'

- include: osx/compose.yml
  when: docker_install_compose and ansible_os_family == 'Darwin'
