---
- include: debian/docker.yml
  when: ansible_os_family == 'Debian'

- include: osx/docker.yml
  when: ansible_os_family == 'Darwin'

- include: machine.yml
  when: docker_install_machine

- include: compose.yml
  when: docker_install_compose
