---
- name: Install Compose
  get_url: >
    url=https://github.com/docker/compose/releases/download/{{ docker_version_compose }}/docker-compose-Linux-x86_64
    dest={{ docker_utility_root }}/docker-compose
    force=yes
    mode=0755
